CREATE TABLE users (
    id UUID PRIMARY KEY,
    email VARCHAR(225) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT (FALSE),
    created_at TIMESTAMPTZ NOT NULL DEFAULT (NOW()),
    updated_at TIMESTAMPTZ NULL DEFAULT (NULL)
);